---
 - hosts: all
   user: root
   tasks:
     - name: copy of hosts file
       copy: src=/var/lib/jenkins/jobs/MyFirstMavenProject/workspace/sampleapp/pom.xml dest=/home/alepo/jenkins/workspace/MyFirstMavenProject
